# Note that this file is used by Dask configuration
distributed:
  scheduler:
    active-memory-manager:  # See https://distributed.dask.org/en/stable/worker-memory.html#ignore-process-memory
      measure: managed
  worker:
    memory:
      rebalance:
        measure: managed
      target: false
      spill: false
      pause: false
      terminate: false
