name: Run Code Checks

on:
  push:
    branches-ignore: [develop]
    paths:
      - '**'
      - '!docker/**'
      - '!.github/workflows/statistician-*'
      - '!notebooks/**'
      - '!docs/**'
      - '!k8s/**'
      - '!README.md'
    tags:
      - '**'

permissions:
  contents: read
  packages: read

jobs:
  quality:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Run MyPy
        run: uv run mypy -p odc.stats
        shell: bash

  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
          enable-uv-cache: ${{ !startsWith(github.ref, 'refs/tags/') }} # Disable cache on tags to prevent cache poisoning attack

      - name: Run tests
        run: uv run --python ${{ matrix.python-version }} pytest --cov=odc --cov-report=xml --durations=5 tests
        env:
          AWS_REGION: ap-southeast-2

  build-wheels:
    if: |
      github.event_name == 'push' || (github.ref == 'refs/heads/develop'
        && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: wheels_cache
        with:
          path: ./wheels
          key: wheels-${{ github.sha }}

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip freeze

      - name: Build Clean Packages
        run: |
          mkdir -p ./wheels/clean
          python -m build
          mv dist/* ./wheels/clean/
          find ./wheels/clean -type f

  test-wheels:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    container:
      image: ghcr.io/opendatacube/odc-stats:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgis/postgis:18-3.6
        env:
          POSTGRES_DB: opendatacube
          POSTGRES_PASSWORD: opendatacubepassword
          POSTGRES_USER: opendatacube

    needs:
      - build-wheels

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Dependencies
        shell: bash
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
          --fix-missing --no-install-recommends \
          curl \
          gpg \
          nodejs \
          zstd
          python -m pip install --upgrade --no-cache pip
          pip install --no-cache -r \
          tests/requirements.txt
          pip freeze

      - name: Get Wheels from Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: wheels_cache
        with:
          path: ./wheels
          key: wheels-${{ github.sha }}

      - name: Install wheels for testing
        shell: bash
        run: |
          which python
          which datacube

          ls -lh wheels/clean
          pip install --no-deps --no-cache wheels/clean/*whl
          pip check || true
          pip show odc-stats
          which odc-stats | xargs ls -alt
          odc-stats --version

      - name: Run Tests
        shell: bash
        run: |
          echo "Init DB"
          ./tests/init_db.sh

          echo "Running unit tests"
          pytest --cov=. \
          --cov-report=html \
          --cov-report=xml:coverage.xml \
          --timeout=30 tests

          echo "Running integration tests"
          ./tests/integration_test.sh

        env:
          ODC_DEFAULT_DB_HOSTNAME: postgres
          ODC_DEFAULT_DB_USERNAME: opendatacube
          ODC_DEFAULT_DB_PASSWORD: opendatacubepassword
          ODC_DEFAULT_DB_DATABASE: opendatacube
          AWS_NO_SIGN_REQUEST: true
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_REGION: ap-southeast-2
          STAC_API_URL: https://earth-search.aws.element84.com/v0/
          GDAL_HTTP_MAX_RETRY: 5

      - name: Upload Coverage
        if: |
          github.repository == 'opendatacube/odc-stats'

        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          use_oidc: true
          fail_ci_if_error: false
          verbose: false
