name: Statistician Test and Push

env:
  IMAGE_NAME: opendatacube/datacube-statistician

on:
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/statistician-*'
      - '!docker/readme.md'
  push:
    branches:
      - develop
    paths:
      - 'docker/**'
      - '.github/workflows/statistician-*'
      - '!docker/readme.md'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008,DL3002,DL3013,DL3059,SC2102

      - name: Build Statistician image
        timeout-minutes: 20
        shell: bash
        run: |
          cd docker
          docker-compose build

      - name: Run Dockerized Tests for Statistician
        shell: bash
        run: |
          cd docker
          make test

  set_tags:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Changed files
        uses: tj-actions/changed-files@v32
        id: verify-changed-version
        with:
          files: |
              docker/version.txt

      - name: Run step only when version.txt change.
        if: steps.verify-changed-version.outputs.any_changed == 'true'
        run: |
          echo "VERSION=$(cat docker/version.txt)" >> $GITHUB_ENV

      - name: echo dev version for dockhub image tagging
        if: steps.verify-changed-version.outputs.any_changed == 'false'
        run: >-
          echo "VERSION=$(cat docker/version.txt).dev${{ github.run_id }}"
          >> $GITHUB_ENV
    outputs:
      image_tag: ${{ env.VERSION }}

  push_ecr:
    if: github.ref == 'refs/heads/develop'
    needs: [test, set_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::538673716275:role/github-ecr
          aws-region: ap-southeast-2

      - name: Push image to ECR
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: ./docker
          registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest,${{ needs.set_tags.outputs.image_tag }}

  push_public:
    if: github.ref == 'refs/heads/develop'
    needs: [test, set_tags]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push image to dockerhub
        uses: whoan/docker-build-with-cache-action@master
        with:
          context: ./docker
          username: gadockersvc
          password: ${{ secrets.GADOCKERSVC_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest,${{ needs.set_tags.outputs.image_tag }}
