name: Statistician Test and Push

env:
  IMAGE_NAME: emma-dev-test/stats
on:
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/statistician-*'
      - '!docker/readme.md'
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/statistician-*'
      - '!docker/readme.md'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag for this build if it exists
        run: |
          echo "VERSION=$(cat docker/version.txt)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::451924316694:role/github-ecr-emma-test
          aws-region: ap-southeast-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to ECR
        uses: whoan/docker-build-with-cache-action@v4
        with:
          context: ./docker
          session: $AWS_SESSION_TOKEN
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest,${{ env.VERSION }}
      # - name: Push image to ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   run: |
      #     cd ./docker
      #     docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
      #     docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
