---
name: Statistician docker check

on:
  pull_request:
    paths:
      - '.github/workflows/statistician-dive.yml'
      - 'docker/**'
      - '!docker/readme.md'

  push:
    paths:
      - '.github/workflows/statistician-dive.yml'
      - 'docker/**'
      - '!docker/readme.md'

env:
  ORG: odc
  IMAGE: statistician
  DIVE: wagoodman/dive:v0.12.0
  DOCKER_API: 1.37

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: docker/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${ORG}/${IMAGE}:_build ./docker/

      - name: Dive
        run: |
          docker pull ${DIVE}
          docker run -e CI=true -e DOCKER_API_VERSION=${DOCKER_API} --rm -v /var/run/docker.sock:/var/run/docker.sock \
          --mount type=bind,source=${{ github.workspace }}/docker/dive-ci.yml,target=/.dive-ci \
          wagoodman/dive:v0.12.0  --ci-config /.dive-ci ${ORG}/${IMAGE}:_build

      - name: Docker image size check
        uses: wemake-services/docker-image-size-limit@master
        with:
          image: ${{ env.ORG }}/${{ env.IMAGE}}:_build
          size: "3 GiB"
